application:
  name: "GoBI"
  version: "0.0.24"
  last_build: "2026-01-20 15:32:12"

server:
  port: "8080"

database:
  host: "localhost"
  port: "5433"
  user: "root"
  password: "" # Set in .env
  database: "gobi_db"
  schema: "vir"

cursor_pool:
  max_connections: 10
  idle_timeout: "30s"
  absolute_timeout: "5m"
  page_size: 10
  available_page_sizes: [10, 20, 50, 100]




  
